services:
  backend:
    container_name: backend_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ENV=production
    volumes:
      - ./backend/data:/app/data
      - ./backend/embedding:/app/embedding
    restart: on-failure
